---
title: 子线程异常处理.md
date: 2020-08-10 22:46:35
categories: 并发
tags: 并发基础，异常
---


### 栗子1：主线程无法捕获子线程抛出的异常

```java
public class UnCaughtException {
    public static void main(String[] args) {
        try {
            MyThread myThread = new MyThread();
            new Thread(myThread, "thread-1").start();
            new Thread(myThread, "thread-2").start();
            new Thread(myThread, "thread-3").start();
            new Thread(myThread, "thread-4").start();
        } catch (RuntimeException e) {
            System.out.println("主线程捕获了子线程抛出的异常");
        }

    }
}

class MyThread implements Runnable {

    @Override
    public void run() {
        throw new RuntimeException("我是来自子线程的异常");
    }
}
```

执行结果：

因为try..catch..只能捕获当前线程内抛出的异常。

```java
Exception in thread "thread-1" Exception in thread "thread-4" Exception in thread "thread-2" Exception in thread "thread-3" java.lang.RuntimeException: 我是来自子线程的异常
	at threadexception.MyThread.run(UnCaughtException.java:34)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: 我是来自子线程的异常
	at threadexception.MyThread.run(UnCaughtException.java:34)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: 我是来自子线程的异常
	at threadexception.MyThread.run(UnCaughtException.java:34)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: 我是来自子线程的异常
	at threadexception.MyThread.run(UnCaughtException.java:34)
	at java.lang.Thread.run(Thread.java:748)
```

### 栗子2：使用Thread类的UncaughtExceptionHandler接口实现全局捕获异常

```java
// 自定义异常处理器，由于是函数式接口，可以使用Lambda表达式
public class UnCaughtExceptionHandler implements Thread.UncaughtExceptionHandler {
    @Override
    public void uncaughtException(Thread t, Throwable e) {
        System.out.println(t.getName() + "发生了异常;" + e.getMessage());
    }
}
```

```java
public class UnCaughtException {
    public static void main(String[] args) {
        // 设置默认的异常处理器
        Thread.setDefaultUncaughtExceptionHandler(new UnCaughtExceptionHandler());
        MyThread myThread = new MyThread();
        new Thread(myThread, "thread-1").start();
        new Thread(myThread, "thread-2").start();
        new Thread(myThread, "thread-3").start();
        new Thread(myThread, "thread-4").start();

    }
}

class MyThread implements Runnable {

    @Override
    public void run() {
        throw new RuntimeException("我是来自子线程的异常");
    }
}
```

执行结果：

```java
thread-1发生了异常;我是来自子线程的异常
thread-3发生了异常;我是来自子线程的异常
thread-2发生了异常;我是来自子线程的异常
thread-4发生了异常;我是来自子线程的异常
```

### 如何处理子线程出现的异常？

* 在子线程内部try..catch..处理
* 设置Thread默认的异常处理器，全局处理异常